src/uralsteel/uralsteel/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from uralsteel import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visual.urls')),
    # дебаг-тул
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/uralsteel/visual/urls.py
from django.urls import path

from visual.views import MainView, LadlesView, CranesView, LadleAccidentDetailStartingView, \
    CraneAccidentDetailStartingView, AggregateAccidentDetailStartingView, LadleAccidentDetailView, \
    CraneAccidentDetailView, AggregateAccidentDetailView, AggregateAccidentView, LadleAccidentView, CraneAccidentView, \
    AccidentStartingView, EmployeeLoginView, EmployeeLogoutView, AccessDeniedView, PasswordResetConfirm, \
    PasswordResetStarting, PasswordResetComplete, PasswordReset, ChangeEmployeeInfoView, EmployeeProfile, \
    ArchiveReportMessage

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    # ковши
    path('ladles/', LadlesView.as_view(), name='ladles'),
    # краны
    path('cranes/', CranesView.as_view(), name='cranes'),
    # проишествия
    # маршруты начала дополнения
    path('accident/ladle/detail/starting/<int:pk>/', LadleAccidentDetailStartingView.as_view(),
         name='accident-ladle-detail-starting'),
    path('accident/crane/detail/starting/<int:pk>/', CraneAccidentDetailStartingView.as_view(),
         name='accident-crane-detail-starting'),
    path('accident/aggregate/detail/starting/<int:pk>/', AggregateAccidentDetailStartingView.as_view(),
         name='accident-aggregate-detail-starting'),
    # маршруты дополнения отчёта
    path('accident/ladle/detail/<int:pk>/', LadleAccidentDetailView.as_view(), name='accident-ladle-detail'),
    path('accident/crane/detail/<int:pk>/', CraneAccidentDetailView.as_view(), name='accident-crane-detail'),
    path('accident/aggregate/detail/<int:pk>/', AggregateAccidentDetailView.as_view(),
         name='accident-aggregate-detail'),
    # маршруты составления отчёта о проишествии
    path('accident/ladle/', LadleAccidentView.as_view(), name='accident-ladle'),
    path('accident/crane/', CraneAccidentView.as_view(), name='accident-crane'),
    path('accident/aggregate/', AggregateAccidentView.as_view(), name='accident-aggregate'),
    # маршрут начала составления отчёта о проишествии
    path('accident/starting/', AccidentStartingView.as_view(), name='accident-starting'),
    # система разграничения доступа
    # маршруты входа/выхода
    path('login/', EmployeeLoginView.as_view(), name='login'),
    path('logout/', EmployeeLogoutView.as_view(), name='logout'),
    # запрет доступа
    path('access-denied/', AccessDeniedView.as_view(), name='access-denied'),
    # маршруты сброса пароля
    path('profile/password/reset/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(),
         name='pass-reset-confirm'),
    path('profile/password/reset/starting/', PasswordResetStarting.as_view(), name='pass-reset-starting'),
    path('profile/password/reset/complete/', PasswordResetComplete.as_view(), name='pass-reset-complete'),
    path('profile/password/reset/', PasswordReset.as_view(), name='password-reset'),
    # маршрут профиля
    path('profile/<slug:slug>/change/', ChangeEmployeeInfoView.as_view(), name='profile-change'),
    path('profile/<slug:slug>/', EmployeeProfile.as_view(), name='profile'),
    # маршрут уведомления об отправке архивного отчёта на почту
    path('archive-report/', ArchiveReportMessage.as_view(), name='archive-report'),
]

src/uralsteel/visual/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify


class Employees(AbstractUser):
    """Модель работника"""

    POSTS_CHOICES = (
        ('MS', 'Master'),
        ('MH', 'Mechanic'),
        ('DT', 'Dispatcher'),
    )

    def get_photo_path(self, filename):
        # получения пути сохранения фото
        username = self.username
        return f'photos/{username}/{filename}'

    def save(self, *args, **kwargs):
        # нужно добавить slug в правильном формате перед сохранением
        if not self.slug:
            self.slug = slugify(f'{self.username}')
        super().save(*args, **kwargs)

    send_messages = models.BooleanField(default=True,
                                        verbose_name='Слать оповещения на почту?')
    photo = models.ImageField(verbose_name='Фото работника',
                              upload_to=get_photo_path,
                              null=True)
    post = models.CharField(max_length=2, choices=POSTS_CHOICES, verbose_name='Должность')
    patronymic = models.CharField(max_length=100, null=True, blank=True, verbose_name='Отчество')
    slug = models.SlugField(max_length=200, unique=True, db_index=True,
                            verbose_name='Слаг')

    class Meta(AbstractUser.Meta):
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'
        app_label = 'visual'

    def __str__(self):
        return f'<{self.username}>'

    def get_absolute_url(self):
        # Формирование ссылки на профиль пользователя
        return reverse('profile', kwargs={'slug': self.slug})


class Aggregates(models.Model):
    """Модель агрегатов (справочная информация)"""

    def get_photo_path(self, filename):
        # получения пути сохранения фото
        return f'photos/aggregates/{filename}'

    title = models.CharField(verbose_name="Название агрегата", max_length=100)
    num_agg = models.CharField(verbose_name="Номер агрегата", max_length=100)
    num_pos = models.CharField(verbose_name="Номер позиции", max_length=100)
    coord_x = models.SmallIntegerField(verbose_name="Координата по Х")
    coord_y = models.SmallIntegerField(verbose_name="Координата по У")
    stay_time = models.TimeField(verbose_name="Время пребывания на агрегате")
    photo = models.ImageField(upload_to=get_photo_path, verbose_name="Фото ковша на агрегате")
    is_broken = models.BooleanField(default=False, null=False, blank=False,
                                    verbose_name="Сломан ли агрегат")

    def __str__(self):
        return f'{self.title}-{self.num_agg}-{self.num_pos}'

    class Meta:
        verbose_name = 'Агрегат'
        verbose_name_plural = 'Агрегаты'


class AggregatesGMP(Aggregates):
    """Модель агрегатов ГМП"""

    class Meta:
        verbose_name = 'Агрегат ГМП'
        verbose_name_plural = 'Агрегаты ГМП'


class AggregatesUKP(Aggregates):
    """Модель агрегатов УКП"""

    class Meta:
        verbose_name = 'Агрегат УКП'
        verbose_name_plural = 'Агрегаты УКП'


class AggregatesUVS(Aggregates):
    """Модель агрегатов УВС"""

    class Meta:
        verbose_name = 'Агрегат УВС'
        verbose_name_plural = 'Агрегаты УВС'


class AggregatesMNLZ(Aggregates):
    """Модель агрегатов МНЛЗ"""

    class Meta:
        verbose_name = 'Агрегат МНЛЗ'
        verbose_name_plural = 'Агрегаты МНЛЗ'


class AggregatesL(Aggregates):
    """Модель агрегатов Лёжек"""

    class Meta:
        verbose_name = 'Лежка'
        verbose_name_plural = 'Лежки'


class AggregatesBurner(Aggregates):
    """Модель агрегатов Горелок"""

    class Meta:
        verbose_name = 'Горелка'
        verbose_name_plural = 'Горелки'


class Routes(models.Model):
    """Модель маршрутов"""

    aggregate_1 = models.ForeignKey('AggregatesGMP', on_delete=models.PROTECT, verbose_name='Номер ГМП')
    aggregate_2 = models.ForeignKey('AggregatesUKP', on_delete=models.PROTECT, verbose_name='Номер УКП')
    aggregate_3 = models.ForeignKey('AggregatesUVS', on_delete=models.PROTECT, verbose_name='Номер УВС')
    aggregate_4 = models.ForeignKey('AggregatesMNLZ', on_delete=models.PROTECT, verbose_name='Номер МНЛЗ')

    def __str__(self):
        return f'{self.aggregate_1}, {self.aggregate_2}, {self.aggregate_3}, {self.aggregate_4}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'


class Cranes(models.Model):
    """Модель кранов"""

    def get_photo_path(self, filename):
        # получения пути сохранения фото
        return f'photos/cranes/{filename}'

    title = models.CharField(verbose_name="Название крана или каретки", max_length=100)
    size_x = models.SmallIntegerField(verbose_name="Размер по Х")
    size_y = models.SmallIntegerField(verbose_name="Размер по У")
    photo = models.ImageField(upload_to=get_photo_path, verbose_name="Фото крана или каретки")
    is_broken = models.BooleanField(default=False, null=False, blank=False,
                                    verbose_name="Сломан ли кран")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Кран'
        verbose_name_plural = 'Краны'


class Ladles(models.Model):
    """Модель ковшей"""

    title = models.CharField(verbose_name="Название ковша", max_length=100)
    is_active = models.BooleanField(default=False, null=False, blank=False,
                                    verbose_name="Активен ли ковш")
    is_broken = models.BooleanField(default=False, null=False, blank=False,
                                    verbose_name="Сломан ли ковш")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Ковш'
        verbose_name_plural = 'Ковши'


class BrandSteel(models.Model):
    """Модель марок стали"""

    title = models.CharField(verbose_name="Марка стали", max_length=100)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Марка стали'
        verbose_name_plural = 'Марки стали'


class DynamicTableAbstract(models.Model):
    """Основная таблица с информацией о перемещении ковшей в реальном времени"""

    ladle = models.ForeignKey('Ladles', on_delete=models.PROTECT, verbose_name='Ковш')
    num_melt = models.CharField(max_length=100, verbose_name='Номер плавки')
    brand_steel = models.ForeignKey('BrandSteel', on_delete=models.PROTECT, max_length=100, verbose_name='Марка стали')
    route = models.ForeignKey('Routes', on_delete=models.PROTECT, verbose_name='Маршрурт')
    aggregate = models.ForeignKey('Aggregates', on_delete=models.PROTECT, verbose_name='Агрегат')
    plan_start = models.DateTimeField(verbose_name='Плановая дата начала')
    plan_end = models.DateTimeField(verbose_name='Плановая дата завершения')
    actual_start = models.DateTimeField(null=True, verbose_name='Фактическая дата начала')
    actual_end = models.DateTimeField(null=True, verbose_name='Фактическая дата завершения')

    def __str__(self):
        return f'{self.num_melt}'

    class Meta:
        abstract = True


class ArchiveDynamicTable(DynamicTableAbstract):
    """Модель архивных записей динамической таблицы"""

    def __str__(self):
        return f'Архивная плавка №{self.num_melt}'

    class Meta:
        verbose_name = 'Архивная плавка'
        verbose_name_plural = 'Архивные плавки'
        ordering = ('-actual_end',)


class ActiveDynamicTable(DynamicTableAbstract):
    """Модель активных записей динамической таблицы"""

    def __str__(self):
        return f'Активная плавка №{self.num_melt}'

    class Meta:
        verbose_name = 'Активная плавка'
        verbose_name_plural = 'Активные плавки'
        ordering = ('-actual_end',)


@deconstructible
class WordCountValidator(object):
    """Валидатор количества слов"""

    def __init__(self, count):
        self.count = count

    def __call__(self, val):
        # Проверка оличества слов
        if len(str(val).split(' ')) < self.count:
            raise ValidationError('Отчёт должен содержать как ' +
                                  'минимум %(count)s слов',
                                  code='not_enough_words',
                                  params={'count': self.count})

    def __eq__(self, other):
        return self.count == other.count


class AccidentsAbstract(models.Model):
    """Модель происшествий"""

    author = models.ForeignKey(Employees, on_delete=models.SET_NULL,
                               null=True, blank=False,
                               verbose_name='Автор отчёта')
    report = models.CharField(max_length=800, validators=[WordCountValidator(10)],
                              null=True, blank=False, default=None,
                              verbose_name='Подробное описание проблемы')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата создания отчёта')

    class Meta:
        abstract = True


def accident_pre_save_dispatcher(sender, **kwargs):
    """Диспетчер выполняющийся перед созданием нового проишествия"""
    instance = kwargs['instance']
    object = instance.object
    # отмечаю кран/ковш/агрегат как сломанный
    object.is_broken = True
    object.save()
    # дальнейшая обработка перестроения маршрутов
    ...


class LadlesAccident(AccidentsAbstract):
    """Модель проишествий ковшей"""
    object = models.ForeignKey(Ladles, on_delete=models.SET_NULL,
                               null=True, blank=False,
                               verbose_name='Ковш')

    def __str__(self):
        return f'Отчёт ковш №{self.object.id} - {self.created_at}'

    class Meta:
        verbose_name = 'Прошествия с ковшом'
        verbose_name_plural = 'Прошествия с ковшами'
        ordering = ('-created_at',)

src/uralsteel/visual/forms.py
from django import forms
from visual.models import Employees, LadlesAccident, CranesAccident, AggregateAccident


class CustomClearableFileInputCU(forms.ClearableFileInput):
    """Виджет для добавления нового фото к форме"""
    initial_text = ''
    template_name = 'widgets/customImageFieldTemplate.html'


class ChangeEmployeeInfoForm(forms.ModelForm):
    """Форма для обновления пользовательских данных"""
    email = forms.EmailField(required=True,
                             label='Адресс электронной почты')
    photo = forms.ImageField(label='Фото (рекомендуемый размер 200x200 px)',
                             widget=CustomClearableFileInputCU(attrs={'id': 'id_photo'}))

    class Meta:
        model = Employees
        fields = ('photo', 'username', 'email',
                  'first_name', 'last_name', 'patronymic',
                  'send_messages')


class AccidentStartingForm(forms.Form):
    """
    Форма начальной стадии написания отчёта о поломке или аварии
    содержит в себе список доступных для выбора элементов
    """
    CHOICES = (
        ('cr', 'Кран'),
        ('la', 'Ковш'),
        ('ag', 'Агрегат')
    )
    accident_type = forms.ChoiceField(choices=CHOICES, label='Что сломалось?')


class AccidentForm(forms.ModelForm):
    """Форма для проишествий"""

    class Meta:
        fields = ('object',)
        exclude = ['created_at', 'author', 'report']


class AccidentDetailForm(forms.ModelForm):
    """Форма для проишествий (подробная)"""
    report = forms.CharField(label='Подробное описание проблемы',
                             help_text='минимум 10 слов, до 800 символов',
                             widget=forms.Textarea)

    class Meta:
        fields = ('object', 'report')
        exclude = ['created_at', 'author']


class LadlesAccidentForm(AccidentForm):
    """Форма проишествий с ковшами"""

    class Meta(AccidentForm.Meta):
        model = LadlesAccident


class LadlesAccidentDetailForm(AccidentDetailForm):
    """Форма проишествий с ковшами (подробная)"""

    class Meta(AccidentDetailForm.Meta):
        model = LadlesAccident


class CranesAccidentForm(AccidentForm):
    """Форма проишествий с кранами"""

    class Meta(AccidentForm.Meta):
        model = CranesAccident


class CranesAccidentDetailForm(AccidentDetailForm):
    """Форма проишествий с кранами (подробная)"""

    class Meta(AccidentDetailForm.Meta):
        model = CranesAccident


class AggregateAccidentForm(AccidentForm):
    """Форма проишествий с агрегатами"""

    class Meta(AccidentForm.Meta):
        model = AggregateAccident


class AggregateAccidentDetailForm(AccidentDetailForm):
    """Форма проишествий с агрегатами (подробная)"""

    class Meta(AccidentDetailForm.Meta):
        model = AggregateAccident

src/uralsteel/visual/templates/visual/access_denied.html
{% extends 'layouts/info_message.html' %}

{% block message %}
Доступ ограничен
{% endblock message %}

src/uralsteel/visual/templates/visual/accident.html
{% extends 'layouts/form.html' %}

{% block form_settings %}
method="post"
{% endblock form_settings %}

{% block buttons %}
<input type="submit" class="primary-btn pointer" value="Сообщить">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/accident_detail.html
{% extends 'layouts/form.html' %}

{% block form_settings %}
method="post"
{% endblock form_settings %}

{% block buttons %}
<input type="submit" class="primary-btn pointer" value="Дополнить отчёт">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/accident_detail_starting.html
{% extends 'layouts/info_message.html' %}

{% load static %}

{% block message %}
Хотите ли вы написать подробное описание проблемы ?
{% endblock message %}

{% block addcontent %}
<div class="flex-line-center">
    <a href="{% url 'main' %}" class="secondary-btn pointer">Нет</a>
    <a href="{{ detail_url }}" class="primary-btn pointer">Да</a>
</div>
{% endblock addcontent %}

src/uralsteel/visual/templates/visual/accident_starting.html
{% extends 'layouts/form.html' %}

{% block form_settings %}
method="post"
{% endblock form_settings %}

{% block buttons %}
<input type="submit" class="primary-btn pointer" value="Далее">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/archive_report_message.html
{% extends 'layouts/info_message.html' %}

{% block message %}
Письмо с отчётом будет отправено на вашу почту в течении нескольких минут!
{% endblock message %}

src/uralsteel/visual/templates/visual/change_employee_info.html
{% extends 'layouts/form.html' %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'visual/css/form.css' %}">
<script src="{% static 'visual/js/profile_change.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.js" integrity="sha512-9KkIqdfN7ipEW6B6k+Aq20PV31bjODg4AA52W+tYtAE0jE0kMx49bjJ3FgvS56wzmyfMUHbQ4Km2b7l9+Y/+Eg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.css" integrity="sha512-hvNR0F/e2J7zPPfLC9auFe3/SE0yG4aJCOd/qxew74NN7eyiSKjr7xJJMu1Jy2wf7FXITpWS1E/RY8yzuXN7VA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock links %}

{% block form_title %}
Обновление данных пользователя {{ user.username }}
{% endblock form_title %}

{% block form_settings %}
method="post" enctype="multipart/form-data" id="change-profile"
{% endblock form_settings %}

{% block myform %}
{% for field in form %}
    <p>{{ field.label }}</p>
    {% if field.help_text %}
        <p>{{ field.help_text }}</p>
    {% endif %}
    <p>{{ field }}</p>
    {% if field.errors %}
        <p>{{ field.errors }}</p>
    {% endif %}
{% endfor %}
{% endblock myform %}

{% block buttons %}
<a class="secondary-form-btn pointer" href="{% url 'profile' slug=user.slug %}">Назад</a>
<input type="submit" class="primary-btn pointer" value="Изменить">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/cranes.html
{% extends 'layouts/schema.html' %}

{% load static %}

{% block addlinks %}
<script src="{% static 'visual/js/cranes.js' %}"></script>
<script>
    {% include 'scripts/csrf_html.html' %}
</script>
{% endblock addlinks %}

src/uralsteel/visual/templates/visual/ladles.html
{% extends 'layouts/schema.html' %}

{% load static %}

{% block addlinks %}
<script src="{% static 'visual/js/ladles.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leader-line/1.0.7/leader-line.min.js" integrity="sha512-0dNdzMjpT6pJdFGF1DwybFCfm3K/lzHhxaMXC/92J9/DZujHlqYFqmhTOAoD0o+LkeEsVK2ar/ESs7/Q2B6wJg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script>
    {% include 'scripts/csrf_html.html' %}
</script>
{% endblock addlinks %}

{% block inputtime %}
<div class="center-container">
    <form type="post" id="timeform">
        {% csrf_token %}
        <input type="submit" value="Выбрать время" class="secondary-btn pointer">
        <input id="timeinput" type="time" {% if timeformvalue %}value="{{timeformvalue}}"{% endif %}>
    </form>
</div>
{% endblock inputtime %}

{% block modal %}
<div class="modal fade" id="ladlesModal" tabindex="-1" aria-labelledby="ladlesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="ladlesModalLabel">Информация о ковше</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">Номер ковша:</div>
                    <div class="col" id="ladle-num"></div>
                </div>
                <div class="row">
                    <div class="col">Номер плавки:</div>
                    <div class="col" id="num-melt"></div>
                </div>
                <div class="row">
                    <div class="col">Марка стали:</div>
                    <div class="col" id="brand"></div>
                </div>
                <div class="row">
                    <div class="col">Текущий агрегат:</div>
                    <div class="col" id="aggregate"></div>
                </div>
                <div class="row">
                    <div class="col">Следующий агрегат:</div>
                    <div class="col" id="next-aggregate"></div>
                </div>
                <div class="row">
                    <div class="col">Плановое начало операции:</div>
                    <div class="col" id="operation-start"></div>
                </div>
                <div class="row">
                    <div class="col">Плановый конец операции:</div>
                    <div class="col" id="operation-end"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<button type="button" class="btn btn-primary" id="modal-button" data-bs-toggle="modal" data-bs-target="#ladlesModal" hidden>Открыть модальное окно</button>

<div class="modal fade" id="ladlesDispatcherModal" tabindex="-1" aria-labelledby="ladlesDispatcherModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="ladlesDispatcherModalLabel">Информационное сообщение</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <div class="row container-fluid">
                    <div class="col">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    </div>
                    <div class="col">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="btn-operation-execute">Подтвердить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<button type="button" class="btn btn-primary" id="modal-dispatcher-button" data-bs-toggle="modal" data-bs-target="#ladlesDispatcherModal" hidden>Открыть модальное окно диспетчера</button>
{% endblock modal %}

src/uralsteel/visual/templates/visual/login.html
{% extends 'layouts/form.html' %}

{% load static %}

{% block form_settings %}method="post"{% endblock form_settings %}

{% block buttons %}
    <a class="secondary-form-btn pointer" href="{% url 'password-reset' %}">Забыли пароль?</a>
    <input type="submit" class="primary-btn pointer" value="Войти">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/password_reset.html
{% extends 'layouts/form.html' %}

{% load static %}

{% block form_title %}
Введите почту, на которую зарегистрирован ваш аккаунт
{% endblock form_title %}

{% block form_settings %}method="post"{% endblock form_settings %}

{% block buttons %}
<input type="submit" class="primary-btn pointer" value="Ввести">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/password_reset_complete.html
{% extends 'layouts/info_message.html' %}

{% load static %}

{% block message %}
Пароль успешно восстановлен!
{% endblock message %}

{% block addcontent %}
<a href="{% url 'login' %}" class="primary-btn pointer">Войти</a>
{% endblock addcontent %}

src/uralsteel/visual/templates/visual/password_reset_confirm.html
{% extends 'layouts/form.html' %}

{% load static %}

{% block form_title %}
Введите новый пароль
{% endblock form_title %}

{% block form_settings %}method="post"{% endblock form_settings %}

{% block buttons %}
<input type="submit" class="primary-btn pointer" value="Ввести">
{% endblock buttons %}

src/uralsteel/visual/templates/visual/profile.html
{% extends 'layouts/basic.html' %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'visual/css/profile.css' %}">
{% endblock links %}

{% block content %}
<h1>Профиль пользователя {{user.username}}</h1>
<div class="info">
    <div class="photo">
        {% if user.photo.url %}
        <img src="{{ user.photo.url }}">
        {% else %}
        <img src="{% static 'visual/css/images/no_photo.png' %}">
        {% endif %}
    </div>
    <div class="text-info">
        <p>{{ user.last_name }} {{ user.first_name }} {{ user.patronymic }}</p>
        <p>{{ user.username }}</p>
        <p>{{ user.email }}</p>
        <p>{{ user.get_post_display }}</p>
    </div>
</div>
<a class="secondary-btn change" href="{% url 'profile-change' slug=user.slug %}">Изменить</a>
{% endblock content %}